[tox]
envlist = py39, py310, py311, py312, lint, format
isolated_build = True

[testenv]
deps = 
    uv
commands = 
    uv sync --dev
    uv run pytest {posargs:tests}

[testenv:lint]
deps = 
    uv
commands = 
    uv sync --dev
    uv run ruff format --check src tests
    uv run ruff check src tests
    uv run mypy src/tilearray

[testenv:format]
deps = 
    uv
commands = 
    uv sync --dev
    uv run ruff format src tests
    uv run ruff check --fix src tests
